# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [11]:
# No code solution (reading)
print(f'{torch.cuda.is_available()=}')

torch.cuda.is_available()=True


### 2. Create a random tensor with shape `(7, 7)`.


In [12]:
# Import torch
import torch
display(f"{torch.__version__=}") # cheking the version of torch



# Create random tensor
random_tensor = torch.rand(7, 7)
print(f"{random_tensor.shape=}")
print(f"{random_tensor=}")
print(f"{random_tensor.device=}")



"torch.__version__='2.5.1+cu124'"

random_tensor.shape=torch.Size([7, 7])
random_tensor=tensor([[0.4542, 0.6485, 0.6217, 0.5025, 0.1941, 0.6223, 0.9834],
        [0.2093, 0.3927, 0.3667, 0.4467, 0.9893, 0.7509, 0.3015],
        [0.6674, 0.4506, 0.7565, 0.2627, 0.1391, 0.4342, 0.9226],
        [0.9381, 0.9783, 0.7689, 0.3950, 0.1889, 0.8745, 0.3070],
        [0.3657, 0.0552, 0.9795, 0.0820, 0.5000, 0.3708, 0.9966],
        [0.2991, 0.0649, 0.5887, 0.5522, 0.7673, 0.5313, 0.6799],
        [0.1067, 0.5287, 0.3378, 0.6862, 0.8721, 0.2196, 0.1377]])
random_tensor.device=device(type='cpu')


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
# Create another random tensor
second_random_tensor = torch.rand(size=(1, 7))
print(f"{second_random_tensor.shape=}")
print(f"{second_random_tensor=}")
print(f"{second_random_tensor.device=}")

# Perform matrix multiplication
result_3 = torch.matmul(random_tensor, second_random_tensor.T)

print(f"Reuslt : {result_3}")


second_random_tensor.shape=torch.Size([1, 7])
second_random_tensor=tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])
second_random_tensor.device=device(type='cpu')
Reuslt : tensor([[1.3368],
        [1.6389],
        [1.2195],
        [1.6927],
        [1.2195],
        [1.4768],
        [1.1558]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
A = torch.rand(size=(7, 7))
B = torch.rand(size=(1, 7))

# Matrix multiply tensors
result_4 = torch.matmul(A, B.T)
print(result_4, result_4.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [38]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'{device=}')

# Create two random tensors on GPU
A = torch.rand(size=(2, 3)).to(device)
B = torch.rand(size=(2, 3)).to(device)

# Check trnsors
print(A)
print(B)


device='cuda'
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [41]:
# Perform matmul on tensor_A and tensor_B
result_7 = torch.matmul(A, B.T)
print(result_7, result_7.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [42]:
# Find max
max_value_result_7 = torch.max(result_7)
print(f"{max_value_result_7=}")

# Find min
min_value_result_7 = torch.min(result_7)
print(f"{min_value_result_7=}")


max_value_result_7=tensor(0.5617, device='cuda:0')
min_value_result_7=tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [43]:
# Find arg max
argmax_result_7 = torch.argmax(result_7)
print(f"{argmax_result_7=}")

# Find arg min
argmin_result_7 = torch.argmin(result_7)
print(f"{argmin_result_7=}")



argmax_result_7=tensor(3, device='cuda:0')
argmin_result_7=tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensor_10 = torch.rand(size=(1, 1, 1, 10))
print(f"{random_tensor_10=}")
print(f"{random_tensor_10.shape=}")


# Remove single dimensions
random_tensor_10_squeezed = random_tensor_10.squeeze()

# Print out tensors and their shapes
print(f"{random_tensor_10_squeezed=}")
print(f"{random_tensor_10_squeezed.shape=}")

random_tensor_10=tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
random_tensor_10.shape=torch.Size([1, 1, 1, 10])
random_tensor_10_squeezed=tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
random_tensor_10_squeezed.shape=torch.Size([10])
